/**
 * Adds one mainnet transaction to `test/fixtures/`. Everything the tests hold
 * the decoder to is read from Koios rather than from our own code (ADR-0012):
 * the chain's reading is the second opinion, and a fixture generated by the
 * thing it tests would prove nothing. `exercises` is the exception — it is a
 * claims list, not an oracle, so it is computed from the decoded body.
 *
 * Usage: node scripts/collect-fixture.mjs <name> <transaction id>
 */
import { writeFileSync } from "node:fs"
import { join } from "node:path"
import { blake2b } from "@noble/hashes/blake2.js"
import { Either } from "effect"
import prettier from "prettier"

import { decodeBech32, decodeTransaction, deriveLovelace, totalOf } from "../dist/index.js"

const KOIOS = "https://api.koios.rest/api/v1"
const SOURCE = "koios api.koios.rest/api/v1 tx_info, mainnet"

/** Mainnet, epoch 651, the same figures `test/support/derivation.ts` holds the suite to. */
const MAINNET = {
  stakeDeposit: 2_000_000n,
  poolDeposit: 500_000_000n,
  drepDeposit: 500_000_000n,
  governanceActionDeposit: 100_000_000_000n,
  minFeeCoefficient: 44n,
  minFeeConstant: 155_381n,
  coinsPerUtxoByte: 4_310n,
  slots: { slot: 4_492_800n, time: 1_596_059_091_000n, slotLength: 1_000n }
}

const toHex = (bytes) => Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("")
const fromHex = (hex) => Uint8Array.from(hex.match(/../g) ?? [], (pair) => Number.parseInt(pair, 16))

const addressHex = (bech32) => {
  const decoded = decodeBech32(bech32)
  if (Either.isLeft(decoded)) throw new Error(`${bech32} is not bech32: ${decoded.left.detail}`)
  return toHex(decoded.right.bytes)
}

/** A stake address's header byte says which kind of credential the 28 bytes after it are. */
const credentialOf = (stakeAddress) => {
  if (stakeAddress === undefined || stakeAddress === null) return null
  const bytes = fromHex(addressHex(stakeAddress))
  return { kind: (bytes[0] >>> 4) % 2 === 0 ? "key" : "script", hash: toHex(bytes.subarray(1)) }
}

/** CIP-129 writes a header byte before the credential: 0x22 a key, 0x23 a script. */
const drepCredentialOf = (drepId) => {
  if (drepId === undefined || drepId === null || !drepId.startsWith("drep1")) return null
  const bytes = fromHex(addressHex(drepId))
  if (bytes.length === 28) return { kind: "key", hash: toHex(bytes) }
  return { kind: bytes[0] === 0x23 ? "script" : "key", hash: toHex(bytes.subarray(1)) }
}

const sleep = (ms) => new Promise((resume) => setTimeout(resume, ms))

/** The explorer rate-limits and drops connections; a retry here is not a retry in the package. */
const post = async (path, body) => {
  for (let attempt = 0; ; attempt++) {
    try {
      const response = await fetch(`${KOIOS}/${path}`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body)
      })
      if (response.status === 429 || response.status >= 500) throw new Error(`${path} answered ${response.status}`)
      if (!response.ok) throw new Error(`${path} answered ${response.status}`)
      return await response.json()
    } catch (error) {
      if (attempt === 5) throw error
      await sleep(2000 * (attempt + 1))
    }
  }
}

/** Koios writes an asset name as hex already; a policy and a name together key a quantity. */
const assetsOf = (list) =>
  (list ?? []).map((one) => ({ policyId: one.policy_id, name: one.asset_name ?? "", quantity: one.quantity }))

const tally = (rows) => {
  const totals = new Map()
  for (const { side, assets } of rows) {
    for (const asset of assets) {
      const key = `${asset.policyId}.${asset.name}`
      const running = totals.get(key) ?? { policyId: asset.policyId, name: asset.name, spent: 0n, received: 0n }
      running[side] += BigInt(asset.quantity)
      totals.set(key, running)
    }
  }
  return [...totals.values()]
    .map((asset) => ({ ...asset, delta: asset.spent - asset.received }))
    .filter((asset) => asset.delta !== 0n)
    .sort((left, right) => (left.policyId + left.name < right.policyId + right.name ? -1 : 1))
    .map((asset) => ({
      policyId: asset.policyId,
      name: asset.name,
      spent: String(asset.spent),
      received: String(asset.received),
      delta: String(asset.delta)
    }))
}

/** What the fixture claims to cover, recomputed by `test/decode-fixtures.test.ts` on every run. */
const exercisesOf = (body) => {
  const found = new Set()
  for (const output of body.outputs) {
    found.add(output.form === "legacy" ? "legacy-output" : "post-alonzo-output")
    if (output.value.assets.length > 0) found.add("native-assets-in-output")
    if (output.datum?._tag === "InlineDatum") found.add("inline-datum")
    if (output.datum?._tag === "DatumHash") found.add("datum-hash")
    if (output.scriptRef !== null) found.add("reference-script")
  }
  for (const certificate of body.certificates) found.add(`certificate:${certificate._tag}`)
  for (const proposal of body.proposalProcedures) found.add(`proposal:${proposal.action.kind}`)
  if (body.withdrawals.length > 0) found.add("withdrawal")
  if (body.mint.length > 0) found.add("mint")
  if (body.mint.some((policy) => policy.assets.some((asset) => asset.quantity < 0n))) found.add("burn")
  if (body.auxiliaryDataHash !== null) found.add("auxiliary-data-hash")
  if (body.scriptDataHash !== null) found.add("script-data-hash")
  if (body.collateralInputs.length > 0) found.add("collateral-inputs")
  if (body.requiredSigners.length > 0) found.add("required-signers")
  if (body.networkId !== null) found.add("network-id")
  if (body.collateralReturn !== null) found.add("collateral-return")
  if (body.totalCollateral !== null) found.add("total-collateral")
  if (body.referenceInputs.length > 0) found.add("reference-inputs")
  if (body.votingProcedures.length > 0) found.add("voting-procedures")
  if (body.currentTreasuryValue !== null) found.add("current-treasury-value")
  if (body.donation !== null) found.add("treasury-donation")
  if (body.validityIntervalStart !== null) found.add("validity-interval-start")
  if (body.validityIntervalEnd !== null) found.add("validity-interval-end")
  return [...found].sort()
}

/**
 * What `test/fixtures` is held to, run before the file is written: a candidate
 * that fails here is one whose reading the suite would reject, and finding that
 * out at collection time is cheaper than finding it out in CI.
 */
const check = (fixture, decoded) => {
  const derived = deriveLovelace({
    transaction: decoded,
    userAddresses: fixture.user.addresses.map(fromHex),
    resolvedInputs: fixture.resolved.map((input) => ({
      input: { transactionId: fromHex(input.transactionId), index: BigInt(input.index) },
      address: fromHex(input.address),
      value: {
        coin: BigInt(input.coin),
        assets: input.assets.map((asset) => ({
          policyId: fromHex(asset.policyId),
          assets: [{ name: fromHex(asset.name), quantity: BigInt(asset.quantity) }]
        }))
      }
    })),
    protocolParameters: MAINNET
  })
  if (Either.isLeft(derived)) throw new Error(`${fixture.name} cannot be derived: ${derived.left.message}`)

  const effects = derived.right
  const fail = (what, ours, theirs) => {
    throw new Error(`${fixture.name}: the chain says ${what} is ${theirs}, this reading says ${ours}`)
  }
  if (String(effects.fee) !== fixture.chain.fee) fail("the fee", effects.fee, fixture.chain.fee)
  if (String(effects.user.spent) !== fixture.user.spent)
    fail("what the user spends", effects.user.spent, fixture.user.spent)
  if (String(effects.user.received) !== fixture.user.received)
    fail("what the user receives", effects.user.received, fixture.user.received)
  if (String(totalOf(effects.deposits) - totalOf(effects.refunds)) !== fixture.chain.deposit)
    fail("deposits less refunds", totalOf(effects.deposits) - totalOf(effects.refunds), fixture.chain.deposit)
  if (effects.unaccounted !== 0n) {
    throw new Error(
      `${fixture.name} leaves ${effects.unaccounted} lovelace unaccounted for, so its reading is incomplete`
    )
  }
}

export const collect = async (name, transactionId) => {
  const [[cbor], [info]] = await Promise.all([
    post("tx_cbor", { _tx_hashes: [transactionId] }).then((rows) => rows.map((row) => row.cbor)),
    post("tx_info", {
      _tx_hashes: [transactionId],
      _inputs: true,
      _metadata: false,
      _assets: true,
      _withdrawals: true,
      _certs: true,
      _scripts: false,
      _bytecode: false,
      _governance: true
    })
  ])
  if (cbor === undefined || info === undefined) throw new Error(`the chain has no ${transactionId}`)

  const decoded = decodeTransaction(fromHex(cbor))
  if (Either.isLeft(decoded)) throw new Error(`${name} was refused: ${decoded.left.message}`)
  const commit = toHex(blake2b(decoded.right.bodyBytes, { dkLen: 32 }))
  if (commit !== transactionId) throw new Error(`${name} hashes to ${commit}, not to its own id`)

  // Whoever holds the inputs is the user, which is who signs in Mode A. The
  // reward account joins them so a withdrawal counts as the user's own.
  const addresses = [
    ...new Set([
      ...info.inputs.map((input) => addressHex(input.payment_addr.bech32)),
      ...info.withdrawals.map((withdrawal) => addressHex(withdrawal.stake_addr))
    ])
  ].sort()
  const owned = new Set(addresses)
  // A Byron output is base58, not bech32, and is never the signer's: the
  // addresses above come from the inputs, where a Byron one would have thrown.
  const mine = (row) => {
    const text = row.payment_addr.bech32
    return text.startsWith("addr") && owned.has(addressHex(text))
  }

  const spent = info.inputs.filter(mine).reduce((sum, input) => sum + BigInt(input.value), 0n)
  const received = info.outputs.filter(mine).reduce((sum, output) => sum + BigInt(output.value), 0n)

  const fixture = {
    name,
    transactionId,
    exercises: exercisesOf(decoded.right.body),
    chain: {
      source: SOURCE,
      blockHeight: info.block_height,
      absoluteSlot: info.absolute_slot,
      timestamp: info.tx_timestamp,
      fee: info.fee,
      totalOutput: info.total_output,
      outputs: info.outputs.length,
      inputs: info.inputs.length,
      collateralInputs: info.collateral_inputs.length,
      referenceInputs: info.reference_inputs.length,
      certificates: [...info.certificates]
        .sort((left, right) => left.index - right.index)
        .map((certificate) => ({
          index: certificate.index,
          type: certificate.type,
          credential: credentialOf(certificate.info?.stake_address),
          pool: certificate.info?.pool_id_hex ?? null,
          drep: certificate.info?.drep_id ?? null,
          drepCredential: drepCredentialOf(certificate.info?.drep_id),
          deposit: certificate.info?.deposit ?? null
        })),
      withdrawals: info.withdrawals.map((withdrawal) => ({
        rewardAccount: addressHex(withdrawal.stake_addr),
        amount: withdrawal.amount
      })),
      mint: assetsOf(info.assets_minted),
      invalidBefore: info.invalid_before,
      invalidAfter: info.invalid_after,
      votingProcedures: info.voting_procedures.length,
      proposalProcedures: info.proposal_procedures.length,
      deposit: info.deposit,
      treasuryDonation: info.treasury_donation
    },
    user: {
      addresses,
      spent: String(spent),
      received: String(received),
      ada: String(spent - received),
      assets: tally([
        ...info.inputs.filter(mine).map((input) => ({ side: "spent", assets: assetsOf(input.asset_list) })),
        ...info.outputs.filter(mine).map((output) => ({ side: "received", assets: assetsOf(output.asset_list) }))
      ])
    },
    // By outpoint, because the explorer does not promise an order and a
    // regenerated fixture that only reshuffles is a diff nobody can read.
    resolved: info.inputs
      .map((input) => ({
        transactionId: input.tx_hash,
        index: input.tx_index,
        address: addressHex(input.payment_addr.bech32),
        coin: input.value,
        assets: assetsOf(input.asset_list)
      }))
      .sort((left, right) =>
        left.transactionId === right.transactionId
          ? left.index - right.index
          : left.transactionId < right.transactionId
            ? -1
            : 1
      ),
    cbor
  }

  check(fixture, decoded.right)
  // Written the way the repository's format check wants it, so adding a fixture
  // is one command rather than one command and a reformat.
  const path = join(import.meta.dirname, "..", "test", "fixtures", `${name}.json`)
  const style = await prettier.resolveConfig(path)
  writeFileSync(path, await prettier.format(JSON.stringify(fixture), { ...style, filepath: path }))
  return fixture
}

const [name, transactionId] = process.argv.slice(2)
if (name !== undefined && transactionId !== undefined) {
  const fixture = await collect(name, transactionId)
  console.log(`${name}: ${fixture.exercises.join(", ")}`)
}
